### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_maint#2]
Hi there,

Strings that are not getting translated.

![chrome_2017-09-05_15-44-25](https://user-images.githubusercontent.com/13456559/30044630-62956ba6-9252-11e7-8e5e-703294f0b275.png)
![chrome_2017-09-05_15-44-38](https://user-images.githubusercontent.com/13456559/30044631-6296384c-9252-11e7-8590-cebc50700120.png)
![chrome_2017-09-05_15-44-04](https://user-images.githubusercontent.com/13456559/30044632-62971c08-9252-11e7-8b8a-1f1c0fbeaa4e.png)

**Comment by cigamit** [comment]
You should be all set to resolve all of these now.
