### ISSUE TITLE
Add Log that notifcation was supress due to maint schedule

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_maint#21]
It would be handy to have a log message that a Event was suppressed due to a maint schedule

**Comment by xmacan** [comment]
What event do you mean?

**Comment by TheWitness** [comment]
A thold or device/up down.  Instead of sending out the warning email/notification.  Log a message.

**Comment by xmacan** [comment]
OK, I will do it

**Comment by xmacan** [comment]
resolved in https://github.com/Cacti/plugin_thold/pull/573#event-8976849530
