### ISSUE TITLE
Fresh install - date picker uses wrong format. 

### ISSUE THREAD

**Issue by dallenk** [Cacti/plugin_maint#23]
**Describe the bug**
Date picker appears to use **date("F j, Y, g:i");** as a format, which results in an error on the new maintenance scheduler page

![image](https://github.com/Cacti/plugin_maint/assets/2725066/67ccfc3a-d96b-41df-bb87-b9016f59049b)

**Comment by TheWitness** [comment]
@xmacan, can you fix this one.  Use the Cacti Date format.

**Comment by xmacan** [comment]
OK, I will look at it
