### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_maint#3]
Came across to this one. Opening a separated issue for better tracking. 

$apply_limits

> 2017/09/05 15:49:12 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/maint/maint.php: 86 schedule_edit)(/plugins/maint/maint.php: 640 thold_hosts)(/plugins/maint/maint.php: 891 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
> --
> 2017/09/05 15:49:12 - ERROR PHP NOTICE in Plugin 'maint': Undefined variable: apply_limits in file: /usr/share/cacti-1.1.21/plugins/maint/maint.php on line: 891

**Comment by cigamit** [comment]
This is resolved in current develop branch.
