### ISSUE TITLE
Error when schedules is active

### ISSUE THREAD

**Issue by rcsmota** [Cacti/plugin_maint#5]
Hi;

When a schedules is active and a device is down I receive the following error on Cacti log

2018/05/17 15:55:13 - CMDPHP SQL Backtrace: (/poller.php: 743  api_plugin_hook)(/lib/plugins.php: 73  api_plugin_run_plugin_hook)(/lib/plugins.php: 170  thold_poller_bottom)(/plugins/thold/includes/polling.php: 41  thold_update_host_status)(/plugins/thold/includes/polling.php: 798  db_execute)(/lib/database.php: 136  db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
2018/05/17 15:55:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near ')' at line  1
2018/05/17 15:55:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064,  SQL:'INSERT INTO plugin_thold_host_failed   (host_id)   VALUES )'

I know is showing plugin_thold but only occurs when a maint schedule is active. 

Thanks.

**Comment by netniV** [comment]
Thanks for the report @rcsmota. There is a flaw in the logic where it attempts to determine if there are hosts to process. If there is, it then checks each host isn't under maintenance.  If a host is under maintenance then it will not process that host.

After checking the available hosts, it does not check if the string has been populated before attempting to add the final bracket and call the db_execute() function to update status. But, that is a THold issue, not a maintenance one so can you open this as an issue on https://github.com/cacti/thold/issues

I know it's a bit cumbersome but it allows us to track the issue properly and commit the code with a reference to the issue.  For now I will close this issue and wait for the new one to be raised.
