### ISSUE TITLE
Undefined Variable on maint.php

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_maint#6]
If you go to Management>Maintenance Schedules, it doesn't matter if it's a new one or an existing one
If you then go to Devices, it shows this notice.

> Notice: Undefined variable: apply_limits in /usr/share/cacti-1.1.37/plugins/maint/maint.php on line 891

**Comment by netniV** [comment]
Hi @jpobeda 

I just cloned the source for the maintenance plugins from https://github.com/cacti/plugins_maint and the line in question is in the middle of an SQL statement so can't be correct.  Have you tried the latest release of the plugin?

**Comment by jpobeda** [comment]
My bad, had upgraded Test installation not the prod one!
